version: '3'
services:
  server:
    build:
      context: .
      target: development
    env_file:
      - ./config/.env
    ports:
      - "4000:4000"
    volumes:
      - "./:/usr/src/app"
      - /usr/src/app/node_modules
    depends_on:
      - db
      
  db:
    image: mongo
    restart: always
    expose:
      - 27018
    ports:
      - "27018:27017"
    volumes:
      - "db-data:/data/db"
    env_file:
      - ./config/.env
    
    
volumes:
  db-data:

