version: '3'
services:
  server:
    build:
      context: .
      target: development
    env_file:
      - ./config/.env
    ports:
      - "4000:4000"
    volumes:
      - "./:/usr/src/app"
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"
    
    
volumes:
  db-data:

